export enum OrderType {
    PRODUCT = 'PRODUCT',        // MARKET
    APPOINTMENT = 'APPOINTMENT',// VET / CLINIC
    PRESCRIPTION = 'PRESCRIPTION', // PHARMACY
    NONE_PRESCRIPTION = 'NONE_PRESCRIPTION', // PHARMACY
    WALLET_CHARGE='WALLET_CHARGE'
}
